// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: book_authors.sql

package pgx

import (
	"context"
)

const setBookAuthor = `-- name: SetBookAuthor :exec
INSERT INTO book_authors (book_id, author_id)
VALUES ($1, $2)
`

type SetBookAuthorParams struct {
	BookID   int64
	AuthorID int64
}

// SetBookAuthor
//
//	INSERT INTO book_authors (book_id, author_id)
//	VALUES ($1, $2)
func (q *Queries) SetBookAuthor(ctx context.Context, arg SetBookAuthorParams) error {
	_, err := q.db.Exec(ctx, setBookAuthor, arg.BookID, arg.AuthorID)
	return err
}

const unsetBookAuthors = `-- name: UnsetBookAuthors :exec
DELETE FROM book_authors
WHERE book_id = $1
`

// UnsetBookAuthors
//
//	DELETE FROM book_authors
//	WHERE book_id = $1
func (q *Queries) UnsetBookAuthors(ctx context.Context, bookID int64) error {
	_, err := q.db.Exec(ctx, unsetBookAuthors, bookID)
	return err
}
