package gqlgen

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.68

import (
	"context"

	"github.com/marc-watters/sqlc-gqlgen-example/v2/pgx"
)

// Authors is the resolver for the authors field.
func (r *bookResolver) Authors(ctx context.Context, obj *pgx.Book) ([]*pgx.Author, error) {
	return r.Repository.ListAuthorsByBookID(ctx, obj.ID)
}

// Book returns BookResolver implementation.
func (r *Resolver) Book() BookResolver { return &bookResolver{r} }

type bookResolver struct{ *Resolver }
